add graphql-endpoint to app

diff --git a/bg-app/Dockerfile b/bg-app/Dockerfile
--- a/bg-app/Dockerfile
+++ b/bg-app/Dockerfile
@@ -2,6 +2,15 @@ ARG NODE_VERSION=22
 
 FROM node:${NODE_VERSION}-slim AS builder
 
+ARG GRAPHQL_ENDPOINT=__NOT_PROVIDED__
+
+ENV GRAPHQL_ENDPOINT=$GRAPHQL_ENDPOINT
+
+RUN if [ "$GRAPHQL_ENDPOINT" = "__NOT_PROVIDED__" ]; then \
+      echo "ERROR: GRAPHQL_ENDPOINT build argument is required" && \
+      exit 1; \
+    fi
+
 WORKDIR /app
 COPY . ./
 
